### ISSUE TITLE
Binding address keep being overwritten on container launch

### ISSUE THREAD

**Issue by GuizmoPhil** [linuxserver/docker-sabnzbd#116]
I'm trying to bind Sabnzbd to `127.0.0.1`.

I can configure it in the settings, but each time I restart the container, it is being overwritten by `::`.

Looking at the log, I see this when the container starts: `Arguments = "/app/sabnzbd/SABnzbd.py" "--config-file" "/config" "--server" "::"`

Is there a way that I can prevent the server string from being overwritten on launch?

Thanks,
Phil

**Comment by Paulus88** [comment]
+1 same issue, seems to be hardcoded in the service at boot
![image](https://user-images.githubusercontent.com/25663775/153008752-25303d97-4aae-4169-b29f-e46876c9a4ed.png)

**Comment by Paulus88** [comment]
> You already found the code. Add `HAS_IPV6=false` as a environment variable...

Oh of course sounds logical, thanks @Roxedus !!

**Comment by GuizmoPhil** [comment]
Thank you @Paulus88 , I've implemented your fix.

**Comment by benjick** [comment]
I did set `HAS_IPV6=false` and I can see my host is `0.0.0.0` but I still get the following error:

> Refused connection with hostname "sabnzbd" from: 172.21.0.4 [Sonarr/3.0.7.1477 (ubuntu 18.04)]

**Comment by aptalca** [comment]
That's sab's hostname block. You need to add `sabnzbd` to the allow list (or whitelist, I forget what they call it)

**Comment by benjick** [comment]
@aptalca thank you! 🙏 that solved it

Docs if anyone ends up here from google like I did: https://sabnzbd.org/wiki/extra/hostname-check.html
